package com.poc.bankingagent.security;

public enum Permission {
    TOOL_ACCOUNT_READ,
    TOOL_CARD_TRANSACTION_READ,
    TOOL_LOAN_RECOMMEND,
    TOOL_TICKET_CREATE,
    TOOL_ASYNC_JOB_READ,
    RESOURCE_SCHEMA_READ,
    RESOURCE_POLICY_READ,
    RESOURCE_KAFKA_TOPIC_READ,
    OPS_AUDIT_READ,
    OPS_JOB_READ,
    OPS_DEAD_LETTER_READ
}
